"""
Drop the existing recipes.db and recreate it with the new 3-table schema,
then seed all 12 recipes from the Larder design.

Run from project root:
    uv run python scripts/migrate.py
"""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from api.database import DB_PATH, get_connection, init_db

RECIPES = [
    {
        "name": "Rigatoni all'Amatriciana",
        "description": None,
        "category": "primi",
        "time_min": 30,
        "servings": 4,
        "kcal": 520,
        "protein_g": 18,
        "carbs_g": 62,
        "fat_g": 19,
        "fiber_g": 4,
        "has_meat": True,
        "image_id": "1551183053-bf91a1d81141",
        "tags": ["Comfort", "Tradizionale"],
        "ingredients": [
            ("Rigatoni", 320, "g", "Pasta/Riso"),
            ("Guanciale", 150, "g", "Proteine"),
            ("Pomodori pelati", 400, "g", "Verdure"),
            ("Pecorino romano", 60, "g", "Latticini"),
            ("Cipolla", 1, None, "Verdure"),
            ("Olio evo", 2, "cucchiai", "Condimenti"),
            ("Peperoncino", 1, None, "Spezie"),
            ("Sale", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Rosola il guanciale a dadini in padella finché croccante, poi mettilo da parte.",
            "Nello stesso grasso soffriggi la cipolla tritata con il peperoncino.",
            "Aggiungi i pomodori pelati schiacciati e cuoci 15 minuti.",
            "Lessa i rigatoni al dente e scolali tenendo un mestolo d'acqua.",
            "Manteca pasta e sugo, unisci il guanciale e il pecorino. Servi subito.",
        ],
    },
    {
        "name": "Spaghetti alle Vongole",
        "description": None,
        "category": "primi",
        "time_min": 25,
        "servings": 4,
        "kcal": 540,
        "protein_g": 22,
        "carbs_g": 64,
        "fat_g": 16,
        "fiber_g": 3,
        "has_meat": False,
        "image_id": "1563379926898-05f4575a45d8",
        "tags": ["Veloce", "Mare"],
        "ingredients": [
            ("Spaghetti", 320, "g", "Pasta/Riso"),
            ("Vongole", 800, "g", "Proteine"),
            ("Aglio", 2, "spicchi", "Verdure"),
            ("Prezzemolo", 1, "mazzo", "Verdure"),
            ("Vino bianco", 100, "ml", "Condimenti"),
            ("Olio evo", 3, "cucchiai", "Condimenti"),
            ("Peperoncino", 1, None, "Spezie"),
        ],
        "steps": [
            "Fai spurgare le vongole in acqua e sale per un'ora.",
            "Apri le vongole in padella con aglio e olio, sfuma con il vino.",
            "Filtra e tieni il liquido delle vongole.",
            "Lessa gli spaghetti molto al dente e finisci la cottura nel liquido.",
            "Salta con vongole e prezzemolo, completa con un filo d'olio a crudo.",
        ],
    },
    {
        "name": "Risotto ai Porcini",
        "description": None,
        "category": "primi",
        "time_min": 40,
        "servings": 4,
        "kcal": 480,
        "protein_g": 11,
        "carbs_g": 71,
        "fat_g": 14,
        "fiber_g": 5,
        "has_meat": False,
        "image_id": "1476124369491-e7addf5db371",
        "tags": ["Vegetariano", "Cremoso"],
        "ingredients": [
            ("Riso Carnaroli", 320, "g", "Pasta/Riso"),
            ("Funghi porcini", 300, "g", "Verdure"),
            ("Brodo vegetale", 1, "L", "Condimenti"),
            ("Cipolla", 1, None, "Verdure"),
            ("Vino bianco", 80, "ml", "Condimenti"),
            ("Parmigiano", 50, "g", "Latticini"),
            ("Burro", 30, "g", "Latticini"),
            ("Prezzemolo", None, "q.b.", "Verdure"),
        ],
        "steps": [
            "Trifola i porcini con un po' di aglio e prezzemolo, tieni da parte.",
            "Tosta il riso con la cipolla, sfuma con il vino bianco.",
            "Aggiungi il brodo caldo poco alla volta mescolando.",
            "A metà cottura unisci i porcini.",
            "Manteca fuori dal fuoco con burro e parmigiano. Lascia riposare un minuto.",
        ],
    },
    {
        "name": "Pollo alla Cacciatora",
        "description": None,
        "category": "secondi",
        "time_min": 55,
        "servings": 4,
        "kcal": 610,
        "protein_g": 41,
        "carbs_g": 12,
        "fat_g": 38,
        "fiber_g": 3,
        "has_meat": True,
        "image_id": "1432139555190-58524dae6a55",
        "tags": ["Tradizionale"],
        "ingredients": [
            ("Pollo a pezzi", 1000, "g", "Proteine"),
            ("Pomodori pelati", 400, "g", "Verdure"),
            ("Olive nere", 100, "g", "Verdure"),
            ("Cipolla", 1, None, "Verdure"),
            ("Carota", 1, None, "Verdure"),
            ("Sedano", 1, "costa", "Verdure"),
            ("Rosmarino", 2, "rametti", "Spezie"),
            ("Vino rosso", 150, "ml", "Condimenti"),
            ("Olio evo", 3, "cucchiai", "Condimenti"),
        ],
        "steps": [
            "Rosola i pezzi di pollo nell'olio finché dorati.",
            "Aggiungi il trito di cipolla, carota e sedano.",
            "Sfuma con il vino rosso e lascia evaporare.",
            "Unisci pomodori, olive e rosmarino.",
            "Cuoci coperto a fuoco basso per 40 minuti, aggiustando di sale.",
        ],
    },
    {
        "name": "Parmigiana di Melanzane",
        "description": None,
        "category": "secondi",
        "time_min": 75,
        "servings": 6,
        "kcal": 430,
        "protein_g": 16,
        "carbs_g": 24,
        "fat_g": 29,
        "fiber_g": 6,
        "has_meat": False,
        "image_id": "1619895092538-128341789043",
        "tags": ["Vegetariano", "Forno"],
        "ingredients": [
            ("Melanzane", 1000, "g", "Verdure"),
            ("Passata di pomodoro", 700, "g", "Verdure"),
            ("Mozzarella", 300, "g", "Latticini"),
            ("Parmigiano", 100, "g", "Latticini"),
            ("Basilico", 1, "mazzo", "Verdure"),
            ("Farina", 100, "g", "Altro"),
            ("Olio per friggere", 500, "ml", "Condimenti"),
            ("Sale", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Affetta le melanzane, salale e falle spurgare 30 minuti.",
            "Friggile dorate e asciugale su carta.",
            "Prepara un sugo semplice con la passata e il basilico.",
            "Alterna in teglia melanzane, sugo, mozzarella e parmigiano.",
            "Inforna a 180°C per 30 minuti. Fai riposare prima di servire.",
        ],
    },
    {
        "name": "Ossobuco alla Milanese",
        "description": None,
        "category": "secondi",
        "time_min": 120,
        "servings": 4,
        "kcal": 680,
        "protein_g": 52,
        "carbs_g": 14,
        "fat_g": 42,
        "fiber_g": 1,
        "has_meat": True,
        "image_id": "1544025162-d76694265947",
        "tags": ["Della domenica"],
        "ingredients": [
            ("Ossobuco di vitello", 4, None, "Proteine"),
            ("Brodo di carne", 500, "ml", "Condimenti"),
            ("Vino bianco", 150, "ml", "Condimenti"),
            ("Cipolla", 1, None, "Verdure"),
            ("Carota", 1, None, "Verdure"),
            ("Sedano", 1, "costa", "Verdure"),
            ("Burro", 40, "g", "Latticini"),
            ("Farina", 50, "g", "Altro"),
            ("Prezzemolo e limone", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Infarina gli ossibuchi e rosolali nel burro.",
            "Aggiungi il trito di verdure e fai appassire.",
            "Sfuma con il vino bianco.",
            "Unisci il brodo, copri e cuoci a fuoco bassissimo 1 ora e mezza.",
            "Completa con la gremolada di prezzemolo, aglio e scorza di limone.",
        ],
    },
    {
        "name": "Zuppa di Lenticchie",
        "description": None,
        "category": "zuppe",
        "time_min": 35,
        "servings": 4,
        "kcal": 280,
        "protein_g": 17,
        "carbs_g": 42,
        "fat_g": 5,
        "fiber_g": 14,
        "has_meat": False,
        "image_id": "1547592180-85f173990554",
        "tags": ["Vegetariano", "Veloce"],
        "ingredients": [
            ("Lenticchie", 300, "g", "Altro"),
            ("Pomodori pelati", 200, "g", "Verdure"),
            ("Carota", 2, None, "Verdure"),
            ("Sedano", 2, "coste", "Verdure"),
            ("Cipolla", 1, None, "Verdure"),
            ("Brodo vegetale", 1, "L", "Condimenti"),
            ("Rosmarino", 1, "rametto", "Spezie"),
            ("Olio evo", 2, "cucchiai", "Condimenti"),
        ],
        "steps": [
            "Soffriggi il trito di carota, sedano e cipolla nell'olio.",
            "Aggiungi le lenticchie e tostale un minuto.",
            "Unisci i pomodori e il rosmarino.",
            "Copri con il brodo caldo e cuoci 25 minuti.",
            "Aggiusta di sale e servi con un filo d'olio a crudo.",
        ],
    },
    {
        "name": "Minestrone della Casa",
        "description": None,
        "category": "zuppe",
        "time_min": 45,
        "servings": 6,
        "kcal": 240,
        "protein_g": 9,
        "carbs_g": 38,
        "fat_g": 6,
        "fiber_g": 11,
        "has_meat": False,
        "image_id": "1604908176997-125f25cc6f3d",
        "tags": ["Vegetariano"],
        "ingredients": [
            ("Zucchine", 2, None, "Verdure"),
            ("Carote", 2, None, "Verdure"),
            ("Patate", 2, None, "Verdure"),
            ("Fagioli borlotti", 200, "g", "Altro"),
            ("Sedano", 2, "coste", "Verdure"),
            ("Pomodori", 2, None, "Verdure"),
            ("Pasta corta", 150, "g", "Pasta/Riso"),
            ("Brodo vegetale", 1500, "ml", "Condimenti"),
            ("Parmigiano", None, "q.b.", "Latticini"),
        ],
        "steps": [
            "Taglia tutte le verdure a cubetti regolari.",
            "Falle stufare qualche minuto nell'olio.",
            "Copri con il brodo e cuoci 25 minuti.",
            "Aggiungi la pasta e i fagioli, cuoci finché al dente.",
            "Servi con parmigiano grattugiato e olio a crudo.",
        ],
    },
    {
        "name": "Insalata di Finocchi e Arance",
        "description": None,
        "category": "contorni",
        "time_min": 15,
        "servings": 4,
        "kcal": 160,
        "protein_g": 3,
        "carbs_g": 18,
        "fat_g": 9,
        "fiber_g": 6,
        "has_meat": False,
        "image_id": "1505253716362-afaea1d3d1af",
        "tags": ["Vegetariano", "Veloce", "Fresco"],
        "ingredients": [
            ("Finocchi", 2, None, "Verdure"),
            ("Arance", 2, None, "Verdure"),
            ("Olive nere", 50, "g", "Verdure"),
            ("Olio evo", 2, "cucchiai", "Condimenti"),
            ("Sale", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Affetta finemente i finocchi con la mandolina.",
            "Pela a vivo le arance e ricava gli spicchi.",
            "Unisci finocchi, arance e olive in una ciotola.",
            "Condisci con olio, sale e qualche goccia del succo d'arancia.",
            "Lascia insaporire 10 minuti prima di servire.",
        ],
    },
    {
        "name": "Caprese di Bufala",
        "description": None,
        "category": "contorni",
        "time_min": 10,
        "servings": 4,
        "kcal": 220,
        "protein_g": 14,
        "carbs_g": 6,
        "fat_g": 16,
        "fiber_g": 1,
        "has_meat": False,
        "image_id": "1592417817098-8fd3d9eb14a5",
        "tags": ["Vegetariano", "Veloce"],
        "ingredients": [
            ("Mozzarella di bufala", 250, "g", "Latticini"),
            ("Pomodori", 4, None, "Verdure"),
            ("Basilico", 1, "mazzo", "Verdure"),
            ("Olio evo", 2, "cucchiai", "Condimenti"),
            ("Origano", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Affetta i pomodori e la mozzarella a fette spesse.",
            "Alternale su un piatto da portata.",
            "Distribuisci le foglie di basilico.",
            "Condisci con olio, origano e un pizzico di sale.",
            "Servi a temperatura ambiente.",
        ],
    },
    {
        "name": "Tiramisù della Nonna",
        "description": None,
        "category": "dolci",
        "time_min": 30,
        "servings": 8,
        "kcal": 390,
        "protein_g": 7,
        "carbs_g": 43,
        "fat_g": 21,
        "fiber_g": 1,
        "has_meat": False,
        "image_id": "1571877227200-a0d98ea607e9",
        "tags": ["Dolce", "Classico"],
        "ingredients": [
            ("Savoiardi", 300, "g", "Altro"),
            ("Mascarpone", 500, "g", "Latticini"),
            ("Uova", 4, None, "Proteine"),
            ("Zucchero", 100, "g", "Altro"),
            ("Caffè", 300, "ml", "Condimenti"),
            ("Cacao amaro", None, "q.b.", "Spezie"),
        ],
        "steps": [
            "Monta i tuorli con lo zucchero, unisci il mascarpone.",
            "Incorpora delicatamente gli albumi montati a neve.",
            "Inzuppa i savoiardi nel caffè freddo.",
            "Alterna strati di savoiardi e crema in una pirofila.",
            "Spolvera di cacao e lascia in frigo almeno 4 ore.",
        ],
    },
    {
        "name": "Pancakes alla Ricotta",
        "description": None,
        "category": "colazione",
        "time_min": 20,
        "servings": 4,
        "kcal": 310,
        "protein_g": 14,
        "carbs_g": 34,
        "fat_g": 13,
        "fiber_g": 2,
        "has_meat": False,
        "image_id": "1567620905732-2d1ec7ab7445",
        "tags": ["Veloce", "Dolce"],
        "ingredients": [
            ("Ricotta", 250, "g", "Latticini"),
            ("Uova", 3, None, "Proteine"),
            ("Farina", 150, "g", "Altro"),
            ("Latte", 100, "ml", "Latticini"),
            ("Zucchero", 40, "g", "Altro"),
            ("Lievito", 1, "bustina", "Altro"),
            ("Miele", None, "q.b.", "Condimenti"),
        ],
        "steps": [
            "Mescola ricotta, tuorli, latte e zucchero.",
            "Unisci farina e lievito setacciati.",
            "Incorpora gli albumi montati a neve.",
            "Cuoci piccoli pancake in padella antiaderente.",
            "Servi caldi con un filo di miele.",
        ],
    },
]


def migrate():
    if DB_PATH.exists():
        DB_PATH.unlink()
        print(f"Dropped {DB_PATH}")

    init_db()
    print("Schema created.")

    conn = get_connection()
    for r in RECIPES:
        cursor = conn.execute(
            """INSERT INTO recipes
                   (name, description, category, time_min, servings,
                    kcal, protein_g, carbs_g, fat_g, fiber_g,
                    has_meat, image_id, tags)
               VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)""",
            (
                r["name"], r["description"], r["category"], r["time_min"],
                r["servings"], r["kcal"], r["protein_g"], r["carbs_g"],
                r["fat_g"], r["fiber_g"], int(r["has_meat"]),
                r["image_id"], json.dumps(r["tags"]),
            ),
        )
        rid = cursor.lastrowid
        for name, qty, unit, macro in r["ingredients"]:
            conn.execute(
                "INSERT INTO recipe_ingredients (recipe_id, name, quantity, unit, macro_group) VALUES (?,?,?,?,?)",
                (rid, name, qty, unit, macro),
            )
        for i, step in enumerate(r["steps"], 1):
            conn.execute(
                "INSERT INTO recipe_steps (recipe_id, step_number, text) VALUES (?,?,?)",
                (rid, i, step),
            )
    conn.commit()
    conn.close()
    print(f"Seeded {len(RECIPES)} recipes.")


if __name__ == "__main__":
    migrate()
